### ISSUE TITLE
concat ressource

### ISSUE THREAD

**Issue by linuxmail** [jake-dog/puppet-resource_tree#4]
Hello,

we using the awesome module for adHoc creating files and install packages. Is it also possible to move our concat parts to hiera and for ressource "file" to use templates ?

Thanks for the really cool work :-)

**Comment by jake-dog** [comment]
Glad you like it!

You can definitely use puppetlabs/concat with resource_tree.  I threw this example together quickly on a puppet 3.8.7 VM to loosely emulate the example from the [concat readme](https://github.com/puppetlabs/puppetlabs-concat#maintain-a-list-of-the-major-modules-on-a-node) (**note**: *the use of `scope` is not compatible between puppet versions and is for demonstration purposes only*):
```yaml
concat_example:
    concat:
      '/tmp/concat_example.txt': {}
    concat::fragment:
      'example_header':
        target: '/tmp/concat_example.txt'
        content: |+
          Puppet modules on this server:

        order: '01'
      'example_middle':
        target: '/tmp/concat_example.txt'
        content: 'rt_eval::scope.compiler.catalog.classes.join("\n")'
        order: '10'
```

The resulting file, `/tmp/concat_example.txt`, looked like this on the 3.8.7 VM:
```plain
Puppet modules on this server:

settings
default
puppet::params
puppet
puppet::config
puppet::agent
puppet::agent::install
puppet::agent::config
puppet::agent::service
resource_tree
concat::setup
stdlib
stdlib::stages```
```

Now I'm guessing based on your question that you wish to combine puppetlabs/concat with templates using resource_tree, which is possible, but it's a bit complicated.  Basically we adopt the strategy from the [resource_tree readme](https://github.com/jake-dog/puppet-resource_tree#creating-multiple-files-with-templates), but combine it with the aforementioned concat example:

```yaml
user_entry_template: |
  <% username = @name[17..-1] -%>
  <% config = scope.function_hiera(['users', {}]).fetch(username, {}) -%>
  <%= username %> is totally <%= config["iscool"]? "" : "not " %>cool!

users:
  bob:
    iscool: false
    order: '02'
  sally:
    iscool: true
    order: '01'

resource_tree::collections:
  concat_example:
    concat:
      '/tmp/concat_example.txt': {}
    concat::fragment: |
      Hash[hiera('users').map{|k,v|
        ["#{k}",
          {
            "target" => "/tmp/concat_example.txt",
            "content" => "rt_eval::inline_template(hiera(\"user_entry_template\"))",
            "order" => v["order"],
          }
        ]
      }]
```

Which produces the file, `/tmp/concat_example.txt`, with contents:
```text
sally is totally cool!
bob is totally not cool!
```

If you ask me that is wayyy too complicated, and it also becomes rather difficult to maintain.

A better approach may be to just build the file with ruby and avoid puppetlabs/concat altogether, eg:
```yaml
users:
  bob:
    iscool: false
  sally:
    iscool: true

resource_tree::collections:
  not_concat_example:
    file:
      '/tmp/not_concat_example.txt':
        content: |
          rt_eval::hiera('users').map{|user,config|
           %(#{user} is totally #{config["iscool"]? "" : "not "}cool!)
          }.join("\n")
```

Which produces the same output as before, albeit the order of elements wasn't preserved and is left as an exercise for the user.
